### ISSUE TITLE
Enable going back to search list

### ISSUE THREAD

**Issue by Vingolf** [kyjus25/radiobrowser#3]
If you have a search list and go to the station history of any item, 
there is no possibility to go back to the search results.
If you go back with the browser button, the search list is empty.

**Comment by kyjus25** [comment]
Thanks for your feedback! The way that the site is currently set up, I was not able to come up with a simple solution for redirecting the user back to a previous "snapshot" of the page without reformatting the structure in a way that ensures the station table never deconstructs when navigating to the history page.

However, I have instead moved the history to a modal rather than a separate page, that way the user's search results are not lost. Additionally, I have overhauled the search params so that they appear in the URL for easy copy/pasting and link transfer.

**Comment by Vingolf** [comment]
> Thanks for your feedback! 
> However, I have instead moved the history to a modal rather than a separate page,
> that way the user's search results are not lost. 
That's a good solution!
There are two more issues I want to mention:
1. Searching is not possible at all [perhaps something went wrong yesterday] ;-)
For the other one, I start a new issue.
